### ISSUE TITLE
Sign here to help!

### ISSUE THREAD

**Issue by aeneasr** [ory/hive#2]

**Comment by sadysnaat** [comment]
Count me in.

**Comment by aeneasr** [comment]
👏

**Comment by yiannistri** [comment]
Happy to help out

**Comment by aeneasr** [comment]
For whoever is watching this - there's a solid idea floating around how to make this happen best. I won't give away too much, but I've started prototyping. Stay tuned!

**Comment by techthumb** [comment]
Happy to help

**Comment by mohdalif** [comment]
hope i can help

**Comment by bardiakeyvani** [comment]
What is the status of this project? I will be happy to help🍺

**Comment by aeneasr** [comment]
Working on it:

![image](https://user-images.githubusercontent.com/3372410/52259665-db383980-2923-11e9-952f-be170cb1d594.png)

**Comment by aeneasr** [comment]
You can get a docs sneak peak: https://github.com/ory/docs/pull/99

**Comment by martoio** [comment]
I've been looking for an easy IAM setup for ages. Would love to join if I can be of help!

**Comment by SlevinWasAlreadyTaken** [comment]
Would like to get involved !

**Comment by GuillaumeSmaha** [comment]
The same for me :+1:

**Comment by BradErz** [comment]
👍

**Comment by aeneasr** [comment]
The skelleton is pretty solid now and we've started migrating the source code to this repo. There's still so much work left to be done but we want to be transparent in our development process. You can check the Draft-PR here: https://github.com/ory/hive/pull/22

We will probably not be able to answer a lot of questions as things are still subject to change.

**Comment by veera83372** [comment]
Please count me in

**Comment by aeneasr** [comment]
Thank you! You can all help by engaging with the issues that will be opened here in the future. There still some way to go to provide you all with a working demo that includes hive, the ui, and the other pieces we will be introducing here.

**Comment by tomanovy** [comment]
Hope I can help... 
what kind of help is needed right now? I'm not senior enough to help as a developer... but anything else just let me know (user testing, docs...)

And I can't wait for "some way to provide us with a working demo that includes hive, the ui" and some basic notes how to setup with oauthkeeper,hydra and keto

**Comment by aeneasr** [comment]
Thank you everyone for wanting to help! We're currently preparing the first mvp release. The release will be preceded by a demo that we do with select companies / developers.

If you're interested, here's the sign up: https://docs.google.com/forms/d/e/1FAIpQLSfz_3-Q5gJ9EGNW2AU49yNIQD1cWaMZ9M-KdRiIyGUw4J7mmw/viewform

**Comment by aeneasr** [comment]
Hey everyone! I'm really sorry that we didn't reach out to most of you signed up to the Google Form - unfortunately the notification system didn't work ;)

However, we are making stellar progress on hive and we're closing in on the first ever release. There's obviously lots of work left to be done including docs, but we're using hive successfully in our internal cloud system already.

I am going to close this issue but not because we want to discourage you from participating, but because we feel that the use of this issue has faded!

You can find the v0.0.1 milestone here: https://github.com/ory/hive/milestone/1

Once all issues are solved we will release the first version!
