### ISSUE TITLE
Dealing with missing data when using 3rd-party registration

### ISSUE THREAD

**Issue by aeneasr** [ory/hive#23]
Right now, we provide a way to normalize data from e.g. GitHub using JSON Schema. Unfortunately, this can not cover all of the use cases, including:

- Adding required user profile info such as date of birth
- Asking for consent regarding Terms of Service and marketing emails

Other solutions offload this to the UI and e.g. grey out the button "sign up with ..." when the consent box is not ticked. I'm not sure how well that works with "sign in with ..." when no account exists. This is obviously not a great system because the validation should be done server side so that it stays consistent across UI implementations.

One possibility would be to have a "profile completion" page or handler or whatever that can deal with this. Maybe this is a hook?

**Comment by ermik** [comment]
stale, you're being unreasonable.

**Comment by aeneasr** [comment]
Haha yeah...

**Comment by aeneasr** [comment]
## hook

Basically, the hook would intercept the request, forward it to another ui endpoint. the ui endpoint would either work with the public API (how? csrf? session?) to update the identity data or with the admin port to update it in a "controlled" fashion.

public
- difficult to secure, need to make sure that it's the same user time and time again
- unclear what API to use? would need a new one
- kinda flaky, another ui endpoint? really?
- I don't see a real upside to this for the password registration. but it would be an upside for saml?

## existing registration ui

We could send the form field errors somehow (?) to the registration ui and request to show the fields. we would need another public API endpoint to complete the data. this would be unique to the

**Comment by aeneasr** [comment]
We thought about an "if_validation_fails" hook but the issue here is that we would have to share error state between strategies and hooks.

**Comment by aeneasr** [comment]
Maybe we could replace the auth code link with a POST action that sets some preliminary data before redirecting to the oauth2 provider? then the two things would be merged (priority is data from oidc?).

The RPC module could enrich the data further if need be.

**Comment by aeneasr** [comment]
This is resolved for the selfservice part. For everything else (e.g. Stripe) we'll use hooks -> closing
