### ISSUE TITLE
pool: Comparing email addresses properly

### ISSUE THREAD

**Issue by aeneasr** [ory/hive#3]
* [ ] Should email addresses be compared case-sensitively or not?
* [ ] Should domains from email addresses be compared case-sensitively or not?
* [ ] Are there potential problems with UTF-8 shinanigans? (*"In modern DNS, we now have Internationalized Domain Names (IDN) which allows Unicode characters. The problem is that defining upper- and lowercase can be tricky in languages and character sets outside of ASCII. The intent of domain names is to be case-insensitive, but there may be complications with particular characters. So there is no simple YES or NO answer to your question."*)

**Comment by bardiakeyvani** [comment]
yes,yes

**Comment by aeneasr** [comment]
Closing because no longer relevant
